### ISSUE TITLE
On submission file produces a "something went wrong" message

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#71] opened 2017-02-17 14:21 UTC
In the case of 
http://papyri.info/editor/publications/56741/ddb_identifiers/128802/edit
on the branch of the user 
http://papyri.info/editor/users/mgelmaghrabi
when he tries to submit it he is faced with the SoSOL 404 message

```
We are sorry, but something went wrong, we are notified etc.
```

Would you please take a look and make sure that the file is properly submitted so that it appears on the editorial board.

**Comment by ryanfb** [comment] 2017-04-20 18:33
Should be fixed.

Created an issue for the cause of this at sosol/sosol#199.

56747 from dratzan was also in this state, also fixed.

**Closed by ryanfb** 2017-04-20 18:33 UTC
