### ISSUE TITLE
Funny Leiden+ saving behaviour

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#98] opened 2017-11-10 15:03 UTC
I suspect this may have something to do with pre-processing.

The file I will discuss is in finalization and I will not finalize it until the problem has been diagnosed sufficiently to get rid of the behaviour.

http://papyri.info/editor/publications/61998/ddb_identifiers/139425/preview

In line FrB 4 you see 

![bildschirmfoto 2017-11-10 um 16 00 58](https://user-images.githubusercontent.com/612992/32664074-6a76c8a8-c630-11e7-9808-20bb7bf00463.png)

in XML this looks like

`<unclear>Η</unclear><hi rend="supraline">̔́ρωνί</hi>`

If I correct the XML to 

`<hi rend="supraline"><unclear>Ἥ</unclear>ρωνί</hi>` 

and save the file and look at preview I see presented

![bildschirmfoto 2017-11-10 um 15 52 59](https://user-images.githubusercontent.com/612992/32663739-4c0df6a8-c62f-11e7-8c4c-af63214c1135.png)

which is what I want to see. 

If I now return to Leiden+ I see

![bildschirmfoto 2017-11-10 um 15 54 23](https://user-images.githubusercontent.com/612992/32663789-783519e6-c62f-11e7-823a-39d8e57aa214.png)

which looks good. If I now save that file it looks fine in Leiden+

![bildschirmfoto 2017-11-10 um 15 56 31](https://user-images.githubusercontent.com/612992/32663877-c59c16ee-c62f-11e7-9942-b58302b34830.png)

but it once again is presented in ugly fashion

![bildschirmfoto 2017-11-10 um 15 57 41](https://user-images.githubusercontent.com/612992/32663924-edd8d4e4-c62f-11e7-922c-dc34f48bcd97.png)

and the XML has gone back to being ugly

![bildschirmfoto 2017-11-10 um 15 58 30](https://user-images.githubusercontent.com/612992/32663968-191896bc-c630-11e7-941c-e07a838c39eb.png)

and incorrect. 

It would be nice to have this fixed. Not top priority, but I wanted to capture the behaviour.
I can, of course, correct in the XML before finalizing and then everything will be fine.

**Comment by ryanfb** [comment] 2017-11-10 16:49
This seems like another good testcase for papryi/xsugar#10.

**Comment by ryanfb** [comment] 2021-02-24 16:48
Closing as duplicate of papyri/xsugar#10.

**Closed by ryanfb** 2021-02-24 16:48 UTC
