### ISSUE TITLE
Files not properly processed: in Finalization but broken

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#151] opened 2019-05-02 08:58 UTC
Like #103 and #149.

Can you please make this file available for finalization (it is in finalization but broken):

 - [x] http://papyri.info/editor/publications/75797/ddb_identifiers/171971/edit

Can you please assign it to me
http://papyri.info/editor/users/james.cowey

Thanks

**Comment by ryanfb** [comment] 2019-05-09 19:10
This problem is caused by one additional commit somehow making it in after submission (i.e. the issue I just created pointing back to this one). In this case, I'm not sure whether you'd want me to pull the additional commit in before assigning it to a finalizer, or remove the additional commit. Here's the commit contents (removes the convex/concave div structure):
![f985yo66](https://user-images.githubusercontent.com/19781/57479907-8088e380-726c-11e9-8a14-91ec8f3c1d2d.png)

**Comment by jcowey** [comment] 2019-05-09 19:38
I would like to have the convex and concave divs present in what is there to be finalised, please.

**Closed** 2019-05-09 20:14 UTC
