### ISSUE TITLE
XSLT: letter with both underdots and a scribal diacritical

### ISSUE THREAD

**Issue by samosafuz** [papyri/sosol#250] opened 2020-12-06 16:35 UTC
In Leiden+, scribal diacriticals are encoded by adding an extra space before the letter which bears the mark, and by enclosing the mark within parentheses immediately following the letter bearing the mark, e.g.,  ὑ(¨)πὲρ, ὑ(´)πὲρ, or ὑ( ῾)πὲρ.

But when the letter carrying the scribal mark is underdotted, Leiden+ breaks in PE. I have tested the various combinations (i.e., dot + scribal diaeresis, acute, grave, circumflex, lenis, or asper) with hypsilon, and have observed similar behavior with other vowels. 

Although the unclear and /unclear xml tags can be added manually by the finalizer, and although everything displays properly in PN after finalization, this xml cannot be edited and resaved if opened in editor without breaking Leiden+, which renders any such file inaccessible to the majority of users. **Therefore, please adapt XSLT to allow for the combination of underdot and scribal diacritical in Leiden+.**

For an example of the offending xml, see [P.Cair.Masp. 2.67151dupl L604](https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.cair.masp/p.cair.masp.2/p.cair.masp.2.67151dupl.xml#L604).

`     <lb n="264"/>α<unclear>ὐ</unclear>τῷ <hi rend="diaeresis"><unclear>ὑ</unclear></hi>πεθέμην ἐνεχύρου λόγῳ καὶ <hi rend="diaeresis">ὑ</hi>ποθήκης δ<supplied reason="lost">ικαίῳ, καὶ μερίζειν</supplied> `

**Comment by jcowey** [comment] 2020-12-07 15:13
I think that this touches on issues similar to #98.

**Comment by ryanfb** [comment] 2020-12-07 15:54
This is caused by papyri/xsugar#17.

**Comment by ryanfb** [comment] 2021-02-24 16:49
Closing as duplicate of papyri/xsugar#17

**Closed by ryanfb** 2021-02-24 16:49 UTC
