### ISSUE TITLE
Files not properly processed: AStF does not move to Approved

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#24] opened 2016-05-23 14:53 UTC
This is the same behaviour as #10, #12, #14, #16, #18 and #22.

- [ ] http://papyri.info/editor/publications/51036/ddb_identifiers/115856/edit

was voted through with Accept straight to finalization, but landed in Waiting (awaiting another vote).

Would you please make this file available for finalization.

This touches on

sosol#150

So it looks to me as if the newly committed code https://github.com/sosol/sosol/commit/cd09740a91ce69cd8e14e878f6ca43e3c6ec228d has not solved the problem completely.

**Comment by ryanfb** [comment] 2016-05-23 15:44
Dupe of #23

**Closed by ryanfb** 2016-05-23 15:44 UTC
